services:
  karin:
    image: ${KARIN_IMAGE}
    restart: unless-stopped
    ports:
      - "${KARIN_PORTS_HTTP}:7000"
      - "${KARIN_PORTS_GRPC}:7001"
      - "${KARIN_PORTS_MANAGE}:5333"
    volumes:
      - ./plugins:/home/karin/plugins
      - ./data:/home/karin/data
      - ./config:/home/karin/config/config
      - ./npmconfig:/home/karin/config/plugin
    environment:
      - KARIN_SUPPORT_PORT=${SUPPORT_PORT}
      - ENVIRONMENT=global
  
  karin-support:
    image: ${SUPPORT_IMAGE}
    restart: unless-stopped
    ports: 
      - "${SUPPORT_PORT}:7005"