version: '3.8'

services:
  karin:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "${KARIN_PORTS_HTTP}:7000"
      - "${KARIN_PORTS_GRPC}:7001"
      - "${KARIN_PORTS_MANAGE}:5333"
    volumes:
      - ./plugins:/home/karin/plugins
      - ./config:/home/karin/config/config
    environment:
      - KARIN_SUPPORT_PORT=${SUPPORT_PORT}
  
  karin-support:
    image: ${SUPPORT_IMAGE}
    restart: unless-stopped
    ports: 
      - "${SUPPORT_PORT}:7005"